# Generated by Django 3.2.5 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcardtransactionsmodel',
            name='credit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
