# Generated by Django 3.2.5 on 2021-07-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardtransactionsmodel',
            old_name='credit',
            new_name='billPaid',
        ),
        migrations.AddField(
            model_name='creditcardtransactionsmodel',
            name='type_of_txn',
            field=models.CharField(choices=[('debit', 'You spent on credit card'), ('credit', 'Money came back to credit card'), ('bill', 'Bill Payment')], default='debit', max_length=10),
            preserve_default=False,
        ),
    ]
